//
//  GrocerySections.swift
//  Bandharapu_GroceryApp
//
//  Created by Bandharapu,Manish Goud on 4/5/22.
//

import Foundation

struct Grocery {
    var section = ""
    var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let itema = Grocery(section:"Dairy",items_Array:[GroceryItem(itemName:"Milk",itemImage:"Milk",itemInfo:"Milk is a nutrient-rich liquid food It is the primary source of nutrition, in several grades after standardization of the fat level, and possible addition of the bacteria Milk can be broken down into several different categories based on type of product produced, including cream, butter, cheese, infant formula, and yogurt."), GroceryItem(itemName: "Sour Cream", itemImage: "SourCream", itemInfo: "Sour cream or soured cream is a dairy product obtained by fermenting regular cream with certain kinds of lactic acid bacteria. The bacterial culture, which is introduced either deliberately or naturally, sours and thickens the cream, Sour cream is often used as a garnish or topping for chili, soups, and stews, as well as Mexican favorites like nachos and burritos. Sour cream dips work well for potato chips and fruit and vegetable platters."), GroceryItem(itemName: "Cheese", itemImage: "Cheese", itemInfo: "Natural cheese is a fermented food made from four basic ingredients including milk, salt, “good bacteria,” and an enzyme called rennet. Cheesemakers use different proportions of this foundational formula coupled with different aging processes to create a variety of cheeses of differing textures, flavors and colors."), GroceryItem(itemName: "Whey", itemImage: "Whey", itemInfo: "Whey is a protein found naturally in milk. Cheese is made from milk, and during the process of making cheese, the milk is separated into solids called curds and into a protein-rich liquid called whey. While the curds are formed into cheese, the whey is pasteurized and dried into whey protein powder for various uses."), GroceryItem(itemName: "Yogurt", itemImage: "Yogurt", itemInfo: "Yogurt is made from milk through fermentation of milk by adding the cultures Lactobacillus bulgaricus and Streptococcus thermophilus. As the cultures grow, the milk thickens and takes on a tangy quality, resulting in the creamy yogurt we know and love. The longer the yogurt is strained, the thicker it will be like Greek- or Icelandic-style yogurts.")] )

let itemb = Grocery(section:"Produce",items_Array:[GroceryItem(itemName:"Arugula",itemImage:"Arugula",itemInfo:"Arugula provides a good source of vitamins A and C, both of which are powerful antioxidants and help to maintain a healthy immune system. Vitamin A is also responsible for cell growth, healthy vision, and helping to maintain kidney, lung, and heart function."), GroceryItem(itemName: "Banana", itemImage: "Banana", itemInfo: "Bananas are one of the most popular fruits in the world. They're full important nutrients, but eating too many could end up doing more harm than good. Too much of any single food may contribute to weight gain and nutrient deficiencies. One to two bananas per day is considered a moderate intake for most healthy people."), GroceryItem(itemName: "GreenBellPeppers", itemImage: "GreenPeppers", itemInfo: "Bell peppers are rich in many vitamins and antioxidants, especially vitamin C and various carotenoids. For this reason, they may have several health benefits, such as improved eye health and reduced risk of several chronic diseases."), GroceryItem(itemName: "YellowOnion", itemImage: "YellowOnion", itemInfo: "Yellow onions are your go-to cooking onions. This onion has yellow skin and a strong flavor due to its high sulphur content, which mellows out during cooking, becoming sweet and flavorful. Its ability to hold up to heat makes it great for caramelizing and roasting."), GroceryItem(itemName: "Black Spanish Radish", itemImage: "BlackRadish", itemInfo: "Spanish black radish, or Raphanus sativus niger, is a large root vegetable that belongs to the Brassicaceae family, also known as the cruciferous vegetable family. It is commonly used for liver and detoxification support, digestion and cholesterol support, and as an antioxidant booster.")] )


let itemc = Grocery(section:"Bakery",items_Array:[GroceryItem(itemName:"Bagels",itemImage:"Bagels",itemInfo:"A bagel is a bread product originating in the Jewish communities of Poland. It is traditionally shaped by hand into the form of a ring from yeasted wheat dough, roughly hand-sized, that is first boiled for a short time in water and then baked."), GroceryItem(itemName: "Donuts", itemImage: "Donut", itemInfo: "A doughnut or donut is a type of food made from leavened fried dough. It is popular in many countries and is prepared in various forms as a sweet snack that can be homemade or purchased in bakeries, supermarkets, food stalls, and franchised specialty vendors."), GroceryItem(itemName: "Cookie", itemImage: "Cookie", itemInfo: "A cookie is a baked or cooked snack or dessert that is typically small, flat and sweet. It usually contains flour, sugar, egg, and some type of oil, fat, or butter. It may include other ingredients such as raisins, oats, chocolate chips, nuts, etc."), GroceryItem(itemName: "Muffins", itemImage: "Muffins", itemInfo: "A muffin is an individually portioned baked product, however the term can refer to one of two distinct items: a part-raised flatbread that is baked and then cooked on a griddle, or an quickbread that is chemically leavened and then baked in a mold."), GroceryItem(itemName: "Pie", itemImage: "Pie", itemInfo: "A pie is a baked dish which is usually made of a pastry dough casing that contains a filling of various sweet or savoury ingredients. Sweet pies may be filled with fruit, nuts, brown sugar, sweetened vegetables, or with thicker fillings based on eggs and dairy.")] )


let itemd = Grocery(section:"SeaFood",items_Array:[GroceryItem(itemName:"Catfish",itemImage:"Catfish",itemInfo:"Catfish are a diverse group of ray-finned fish. Named for their prominent barbels, which resemble a cat's whiskers, catfish range in size and behavior from the three largest species alive."), GroceryItem(itemName: "Crab", itemImage: "Crab", itemInfo: "Crabs are decapod crustaceans of the infraorder Brachyura, which typically have a very short projecting tail, usually hidden entirely under the thorax. They live in all the world's oceans, in fresh water, and on land, are generally covered with a thick exoskeleton, and have a single pair of pincers."), GroceryItem(itemName: "Salmon", itemImage: "Salmon", itemInfo: "Salmon is a common food fish classified as an oily fish with a rich content of protein and omega-3 fatty acids."), GroceryItem(itemName: "Shrimp", itemImage: "Shrimp", itemInfo: "Shrimp are decapod crustaceans with elongated bodies and a primarily swimming mode of locomotion – most commonly Caridea and Dendrobranchiata. More narrow definitions may be restricted to Caridea, to smaller species of either group or to only the marine species."), GroceryItem(itemName: "Tuna", itemImage: "Tuna", itemInfo: "A tuna is a saltwater fish that belongs to the tribe Thunnini, a subgrouping of the Scombridae family. The Thunnini comprise 15 species across five genera, the sizes of which vary greatly, ranging from the bullet tuna up to the Atlantic bluefin tuna, which averages 2 m and is believed to live up to 50 years.")] )


let iteme = Grocery(section:"Pasta/Rice",items_Array:[GroceryItem(itemName:"Brownrice",itemImage:"Brownrice",itemInfo:"Brown rice is a whole grain rice with the inedible outer hull removed. This kind of rice sheds its outer hull or husk but the bran and germ layer remain on, constituting the brown or tan colour of rice. White rice is the same grain without the hull, the bran layer, and the cereal germ."), GroceryItem(itemName: "Lasagna", itemImage: "Lasagna", itemInfo: "Lasagne are a type of pasta, possibly one of the oldest types, made of very wide, flat sheets. Either term can also refer to an Italian dish made of stacked layers of lasagne alternating with fillings ."), GroceryItem(itemName: "Spaghetti", itemImage: "Spaghetti", itemInfo: "Spaghetti is a long, thin, solid, cylindrical pasta. It is a staple food of traditional Italian cuisine. Like other pasta, spaghetti is made of milled wheat and water and sometimes enriched with vitamins and minerals. Italian spaghetti is typically made from durum wheat semolina."), GroceryItem(itemName: "Whiterice", itemImage: "Whiterice", itemInfo: "White rice is milled rice that has had its husk, bran, and germ removed. This alters the flavor, texture and appearance of the rice and helps prevent spoilage, extend its storage life, and makes it easier to digest. After milling, the rice is polished, resulting in a seed with a bright, white, shiny appearance."), GroceryItem(itemName: "Couscous", itemImage: "Couscous", itemInfo: "Couscous is a North African dish of small steamed granules of rolled durum wheat semolina that is traditionally served with a stew spooned on top. Pearl millet, sorghum, Bulgur and other cereals can be cooked in a similar way in other regions and the resulting dishes are also sometimes called couscous.")] )


let grocerys = [itema, itemb, itemc, itemd, iteme]
